# Scoped to this unpublished test package and the pinned libFuzzer wrapper.
# Production dependency license policy is unchanged.
exceptions = [
    { name = "libfuzzer-sys", version = "=0.4.13", allow = ["MIT", "Apache-2.0", "NCSA"] },
]
