//! macOS data-protection Keychain storage for the journal wrapping key.
//!
//! The provider never creates a key during a read. Provisioning is an explicit
//! operation, and reads require exactly one non-synchronizable, data-protection
//! generic-password item with exactly 32 bytes. Keychain error text is reduced
//! to a bounded operation/status message so service names and key material do
//! not reach diagnostics.

use std::fmt;

use security_framework::{
    access_control::{ProtectionMode, SecAccessControl},
    base::Error as SecurityError,
    item::{CloudSync, ItemClass, ItemSearchOptions, Limit, SearchResult},
    passwords::{set_generic_password_options, AccessControlOptions, PasswordOptions},
};

use crate::{crypto::KeyProvider, error::CryptoError};

pub const JOURNAL_KEYCHAIN_SERVICE: &str = "com.alisinadevelo.ghostrace.journal";
pub const JOURNAL_KEYCHAIN_ACCOUNT: &str = "journal-wrapping-key-v1";

/// A provider for one non-synchronizable data-protection generic password.
pub struct MacOsKeychainProvider {
    service: String,
    account: String,
    access_group: Option<String>,
}

impl fmt::Debug for MacOsKeychainProvider {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("MacOsKeychainProvider")
            .field("service", &"<redacted>")
            .field("account", &"<redacted>")
            .field("access_group", &self.access_group.as_ref().map(|_| "<redacted>"))
            .finish()
    }
}

impl MacOsKeychainProvider {
    pub fn new() -> Self {
        Self {
            service: JOURNAL_KEYCHAIN_SERVICE.to_owned(),
            account: JOURNAL_KEYCHAIN_ACCOUNT.to_owned(),
            access_group: None,
        }
    }

    pub fn with_identity(
        service: impl Into<String>,
        account: impl Into<String>,
        access_group: Option<impl Into<String>>,
    ) -> Result<Self, CryptoError> {
        let service = service.into();
        let account = account.into();
        let access_group = access_group.map(Into::into);
        validate_identity("service", &service)?;
        validate_identity("account", &account)?;
        if let Some(group) = access_group.as_deref() {
            validate_identity("access group", group)?;
        }
        Ok(Self { service, account, access_group })
    }

    pub fn service(&self) -> &str {
        &self.service
    }

    pub fn account(&self) -> &str {
        &self.account
    }

    /// Explicitly provision a wrapping key. A missing item is not silently
    /// generated by [`KeyProvider::key`], and an existing item is not replaced.
    pub fn provision(&self, key: [u8; 32]) -> Result<(), CryptoError> {
        if key.iter().all(|byte| *byte == 0) {
            return Err(CryptoError::KeyProvider("key material is invalid".to_owned()));
        }
        if !self.search_items()?.is_empty() {
            return Err(CryptoError::KeyProvider("keychain item already exists".to_owned()));
        }

        let mut options = PasswordOptions::new_generic_password(&self.service, &self.account);
        options.set_access_synchronized(Some(false));
        options.use_protected_keychain();
        let access_control = SecAccessControl::create_with_protection(
            Some(ProtectionMode::AccessibleWhenUnlockedThisDeviceOnly),
            AccessControlOptions::empty().bits(),
        )
        .map_err(|error| map_security_error("configure keychain access", error))?;
        options.set_access_control(access_control);
        if let Some(group) = self.access_group.as_deref() {
            options.set_access_group(group);
        }
        set_generic_password_options(&key, options)
            .map_err(|error| map_security_error("provision keychain item", error))?;

        match self.key() {
            Ok(_) => Ok(()),
            Err(error) => {
                let _ = self.delete();
                Err(error)
            }
        }
    }

    /// Delete the exact non-synchronizable item. This is intended for explicit
    /// key-destruction workflows and test cleanup, not implicit recovery.
    pub fn delete(&self) -> Result<(), CryptoError> {
        let items = self.search_items()?;
        if items.is_empty() {
            return Err(CryptoError::KeyProvider("keychain item is missing".to_owned()));
        }
        if items.len() != 1 {
            return Err(CryptoError::KeyProvider("keychain item is duplicated".to_owned()));
        }
        let mut options = PasswordOptions::new_generic_password(&self.service, &self.account);
        options.set_access_synchronized(Some(false));
        options.use_protected_keychain();
        if let Some(group) = self.access_group.as_deref() {
            options.set_access_group(group);
        }
        security_framework::passwords::delete_generic_password_options(options)
            .map_err(|error| map_security_error("delete keychain item", error))
    }

    fn search_items(&self) -> Result<Vec<Vec<u8>>, CryptoError> {
        let mut search = ItemSearchOptions::new();
        search
            .class(ItemClass::generic_password())
            .service(&self.service)
            .account(&self.account)
            .cloud_sync(CloudSync::MatchSyncNo)
            .limit(Limit::All)
            .load_data(true)
            .ignore_legacy_keychains();
        if let Some(group) = self.access_group.as_deref() {
            search.access_group(group);
        }
        let results =
            search.search().map_err(|error| map_security_error("read keychain item", error))?;
        Ok(results
            .into_iter()
            .filter_map(|result| match result {
                SearchResult::Data(data) => Some(data),
                _ => None,
            })
            .collect())
    }
}

impl Default for MacOsKeychainProvider {
    fn default() -> Self {
        Self::new()
    }
}

impl KeyProvider for MacOsKeychainProvider {
    fn key(&self) -> Result<[u8; 32], CryptoError> {
        let items = self.search_items()?;
        if items.is_empty() {
            return Err(CryptoError::KeyProvider("keychain item is missing".to_owned()));
        }
        if items.len() != 1 {
            return Err(CryptoError::KeyProvider("keychain item is duplicated".to_owned()));
        }
        parse_key_material(&items[0])
    }
}

fn parse_key_material(item: &[u8]) -> Result<[u8; 32], CryptoError> {
    let key: [u8; 32] = item.try_into().map_err(|_| {
        CryptoError::KeyProvider("keychain item has malformed key material".to_owned())
    })?;
    if key.iter().all(|byte| *byte == 0) {
        return Err(CryptoError::KeyProvider(
            "keychain item has malformed key material".to_owned(),
        ));
    }
    Ok(key)
}

fn validate_identity(name: &str, value: &str) -> Result<(), CryptoError> {
    if value.is_empty()
        || value.len() > 255
        || !value.is_ascii()
        || value.bytes().any(|byte| byte.is_ascii_control())
        || value.contains('/')
        || value.contains('\\')
    {
        return Err(CryptoError::KeyProvider(format!("keychain {name} is invalid")));
    }
    Ok(())
}

fn map_security_error(operation: &str, error: SecurityError) -> CryptoError {
    CryptoError::KeyProvider(format!("{operation} failed (status {})", error.code()))
}

#[cfg(test)]
mod tests {
    use super::parse_key_material;

    #[test]
    fn key_material_parser_is_exact_and_rejects_zeroes() {
        assert!(parse_key_material(&[]).is_err());
        assert!(parse_key_material(&[1_u8; 31]).is_err());
        assert!(parse_key_material(&[0_u8; 32]).is_err());
        assert_eq!(parse_key_material(&[9_u8; 32]).expect("valid key"), [9_u8; 32]);
    }
}
